model:
  type: "blip2_llm"  # "blip2_llm", "vit_rugpt2"

  # Настройки для ViT-RuGPT2
  vit_rugpt2:
    model_dir: "model_snapshot"
    model_name: "tuman/vit-rugpt2-image-captioning"

  # Настройки для BLIP-2 + LLM
  blip2_llm:
    blip_model_id: "Salesforce/blip2-itm-vit-g"
    llm_model_id: "mistralai/Mistral-7B-Instruct-v0.2"
    lora_path: null  # или путь к адаптеру, если используется
